version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Build step running"
  post_build:
    commands:
      - echo "Post build step"
