name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Removed pip install step

      - name: Run report script
        run: python scripts/generate_report.py

      - name: Upload generated report
        uses: actions/upload-artifact@v4
        with:
          name: daily-report
          path: report.html
